spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mariadb://svc.sel5.cloudtype.app:31354/lolweb
    hikari:
        username: root
        password: 12011201
        driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://svc.sel5.cloudtype.app:30196/LoLItemSimulation
#    hikari:
#      username: root
#      password: 20231004
#      driver-class-name: org.mariadb.jdbc.Driver
  devtools:
    livereload:
      enabled : true
    remote :
      restart:
        enabled : false
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
app:
  firebase-configuration-file: ./firebaseServiceAccountKey.json
  firebase-bucket: lolweb-ae249.appspot.com
  upload-dir: /home/

server:
  port: 80